ad_show_self_no_view:
    controller: App\Controller\AdController::showSelfNoView
    path: /self

ad_show_self:
    controller: App\Controller\AdController::showSelf
    path: /self/{view}
    requirements:
        view: '%app.ad.views%'
  
ad_add:
    controller: App\Controller\AdController::add
    path: /add

ad_edit:
    controller: App\Controller\AdController::edit
    path: /{ad}/edit
    requirements:
        ad: '\d++'

ad_del:
    controller: App\Controller\AdController::del
    path: /{ad}/del
    requirements:
        ad: '\d++'
