Currency:
  type: object
  config:
    description: "a Community Currency within a Community"
    fields:
      id:
        type: ID!
      name:
        type: String
      community:
        type: Community!
