Query:
  type: object
  config:
    description: "eLAND System for multiple Community Currencies"
    fields:
      me:
        type: User
        resolve: "@=resolver('userMe')"
      user:
        type: User
        args:
          id:
            type: ID!
            description: resolves by id
        resolve: "@=resolver('userById', [args['id']])"
      
      member:
        type: Member
        args:
          id:
            type: ID!
            description: resolves by id
        resolve: "@=resolver('memberById', [args['id']])"
      community:
        type: Community
        args:
          id:
            type: ID!
            description: resolves by id
        resolve: "@=resolver('communityById', [args['id']])"
      currency:
        type: Currency
        args:
          id:
            type: ID!
            description: resolves by id
        resolve: "@=resolver('currencyById', [args['id']])"
      account:
        type: Account
        args:
          id:
            type: ID!
            description: resolves by id
        resolve: "@=resolver('accountById', [args['id']])"