User:
  type: object
  config:
    description: Person with an email login
    fields:
      id:
        type: ID!
      first_name:
        type: String
      last_name:
        type: String
      email:
        type: String!

