root_locale:
    resource: routes_locale.yaml
    prefix: /{_locale}
    requirements:
        _locale: '%app.locales%'

root_no_locale:
    resource: ../src/Controller/NoLocale/
    type: annotation

app_logout:
    path: /logout

root_legacy:
    resource: ../src/Controller/Legacy/
    type: annotation
