g_auth:
    resource: ../src/Controller/Guest/
    type: annotation
    prefix: /{access}
    requirements:
        access: '[giua]'

i_auth:
    resource: ../src/Controller/InterSystem/
    type: annotation
    prefix: /{access}
    requirements:
        access: '[ia]'

u_auth:
    resource: ../src/Controller/User/
    type: annotation
    prefix: /{access}
    requirements:
        access: '[ua]'

a_auth:
    resource: ../src/Controller/Admin/
    type: annotation
    prefix: /{access}
    requirements:
        access: a

no_auth:
    resource: ../src/Controller/NoAuth/
    type: annotation