parameters:
    router.request_context.host: '%env(APP_HOST)%'
    router.request_context.scheme: '%env(APP_SCHEME)%'
    site_name: '%env(SITE_NAME)%'
    app.default_locale: nl
    app.locales: en|nl
    app.user.types: active|new|leaving|direct|intersystem|pre-active|post-active|all
    app.user.views: list|tiles|map
    app.news.views: list|extended
    app.ad.views: list|extended
    app.page: '[a-z0-9-]{3,}'
    app.id: '\d++'
    app.token: '[a-z0-9-]{16}'
    app.uuid: '[0-9a-f-]{36}'
    app.doc: '[0-9a-f]{20}'
    locale: en

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Predis\Client:
        arguments: ['%env(REDIS_URL)']
