giua_auth:
    resource: giua.yaml
    prefix: /{access}
    requirements:
        access: '[giua]'
    methods: [GET]

ua_auth:
    resource: ua.yaml
    prefix: /{access}
    requirements:
        access: '[ua]'
    methods: [GET, POST]

a_auth:
    resource: a.yaml
    prefix: /{access}
    requirements:
        access: a
    methods: [GET, POST]
