support:
    controller: App\Controller\SupportController::form
    path: /support
    methods: [GET|POST]

ua_ad:
    resource: ua/ua_ad.yaml
    prefix: /ads

ua_account:
    resource: ua/ua_account.yaml
    prefix: /accounts

ua_user:
    resource: ua/ua_user.yaml
    prefix: /users

ua_transaction:
    resource: ua/ua_transaction.yaml
    prefix: /transactions

ua_news:
    resource: ua/ua_news.yaml
    prefix: /news

ua_forum:
    resource: ua/ua_forum.yaml
    prefix: /forum

