user_no_view:
    path: /
    controller: App\Controller\UserController::noView
    methods: [GET]

user_index:
    path: /{view}
    controller: App\Controller\UserController::index
    requirements:
        view: '%app.user.views'
    methods: [GET, POST]

user_show:
    path: /{user}
    controller: App\Controller\UserController::show
    requirements: 
        user_type: '%app.user.types%'
        user: '\d+'
    methods: [GET]

